export const siteFilterOptions = {
  heatStressStatus: [
    { value: 0, label: 'No Alert' },
    { value: 1, label: 'Watch' },
    { value: 2, label: 'Warning' },
    { value: 3, label: 'Alert Level 1' },
    { value: 4, label: 'Alert Level 2' },
  ],
  siteOptions: [
    { value: 'activeBuoys', label: 'Active buoys' },
    { value: 'liveStreams', label: 'Live streams' },
    { value: '3DModels', label: '3D Models' },
    { value: 'hoboLoggers', label: 'HOBO loggers' },
    { value: 'waterQuality', label: 'Water quality' },
    { value: 'reefCheckSites', label: 'Reef Check Sites' },
  ],
  species: {
    fish: [
      'Butterflyfish',
      'Haemulidae',
      'Snapper',
      'Barramundi Cod',
      'Bumphead Parrot',
      'Parrotfish',
      'Moray Eel',
      'King Angelfish',
      'Giant Hawkfish',
      'Mexican Hogfish',
      'Algae-farming Damsel',
      'Camotillo',
      'Wrasse',
      'Grunt',
      'Grouper',
    ],
    invertebrates: [
      'Urchin',
      'Diadema',
      'Tripneustes',
      'Edible Sea Cucumber',
      'COTS',
      'Lobster',
      'Spider Crab',
      'Banded Coral Shrimp',
      'Pencil Urchin',
      'Triton',
      'Flamingo Tongue',
      'Gorgonian',
      'Cowries',
      'Sea Fan',
      'Giant Clam',
      'Sea Star',
    ],

    rareAnimals: ['Sharks', 'Turtles', 'Mantas', 'Lionfish'],
  },
  reefComposition: [
    'Hard Coral',
    'Rubble',
    'Recently Killed Coral',
    'Rock',
    'Hard Coral Bleaching',
    'Hard Coral Disease',
    'Soft Coral',
    'Nutrient indicator Algea',
    'Sponge',
    'Sand',
    'Silt/Clay',
    'Other',
    'Fleshy Seaweed',
  ],
  impact: ['None', 'Low', 'Medium', 'High'],
} as const;
