export const mockReefs = [
  {
    name: "Ningaloo Coast",
    week: 3.1,
    sst: 3.1,
    historicalMax: 3.1,
    sstAnomaly: 3.1,
    heatStress: 3.1,
    buoySurface: 3.1,
    buoyBottom: 3.1,
    alertLevel: 4,
  },
  {
    name: "Penguin Cove",
    week: 1.2,
    sst: 1.2,
    historicalMax: 1.2,
    sstAnomaly: 1.2,
    heatStress: 1.2,
    buoySurface: 1.2,
    buoyBottom: 1.2,
    alertLevel: 4,
  },
  {
    name: "Shark Bay",
    week: 3.7,
    sst: 3.7,
    historicalMax: 3.7,
    sstAnomaly: 3.7,
    heatStress: 3.7,
    buoySurface: 3.7,
    buoyBottom: 3.7,
    alertLevel: 4,
  },
  {
    name: "Polar Bear Lair",
    week: 4.8,
    sst: 4.8,
    historicalMax: 4.8,
    sstAnomaly: 4.8,
    heatStress: 4.8,
    buoySurface: 4.8,
    buoyBottom: 4.8,
    alertLevel: 3,
  },
  {
    name: "Parrotfish Hideout",
    week: 0.2,
    sst: 0.2,
    historicalMax: 0.2,
    sstAnomaly: 0.2,
    heatStress: 0.2,
    buoySurface: 0.2,
    buoyBottom: 0.2,
    alertLevel: 3,
  },
  {
    name: "Pirate’s Bay",
    week: 2.5,
    sst: 2.5,
    historicalMax: 2.5,
    sstAnomaly: 2.5,
    heatStress: 2.5,
    buoySurface: 2.5,
    buoyBottom: 2.5,
    alertLevel: 2,
  },
  {
    name: "Ningaloo Coast",
    week: -2.3,
    sst: -2.3,
    historicalMax: -2.3,
    sstAnomaly: -2.3,
    heatStress: -2.3,
    buoySurface: -2.3,
    buoyBottom: -2.3,
    alertLevel: 2,
  },
  {
    name: "Penguin Cove",
    week: 4,
    sst: 4,
    historicalMax: 4,
    sstAnomaly: 4,
    heatStress: 4,
    buoySurface: 4,
    buoyBottom: 4,
    alertLevel: 0,
  },
  {
    name: "Shark Bay",
    week: 1.7,
    sst: 1.7,
    historicalMax: 1.7,
    sstAnomaly: 1.7,
    heatStress: 1.7,
    buoySurface: 1.7,
    buoyBottom: 1.7,
    alertLevel: 0,
  },
  {
    name: "Polar Bear Lair",
    week: -0.3,
    sst: -0.3,
    historicalMax: -0.3,
    sstAnomaly: -0.3,
    heatStress: -0.3,
    buoySurface: -0.3,
    buoyBottom: -0.3,
    alertLevel: 0,
  },
];
