import { CollectionDetails } from "../store/User/types";
import { generateMockReef } from "../mocks/mockReef";

export const customCollection: CollectionDetails = {
  id: 1,
  isPublic: false,
  name: "La Niña",
  userId: 1,
  reefIds: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
  reefs: [
    generateMockReef({
      id: 1,
      name: "Ningaloo Coast",
      regionName: "",
      deployed: true,
      isCollection: true,
      historicMax: 3.1,
      polygon: {
        type: "Point",
        coordinates: [114.995186, -21.379833],
      },
      collectionData: {
        satelliteTemperature: 3.1,
        sstAnomaly: 3.1,
        degreeHeatingDays: 3.1 * 7,
        topTemperature: 3.1,
        bottomTemperature: 3.1,
        weeklyAlert: 4,
      },
    }),
    generateMockReef({
      id: 2,
      name: "Penguin Cove",
      regionName: "",
      deployed: true,
      isCollection: true,
      historicMax: 1.2,
      polygon: {
        type: "Point",
        coordinates: [115.463583, -20.399709],
      },
      collectionData: {
        satelliteTemperature: 1.2,
        sstAnomaly: 1.2,
        degreeHeatingDays: 1.2 * 7,
        topTemperature: 1.2,
        bottomTemperature: 1.2,
        weeklyAlert: 4,
      },
    }),
    generateMockReef({
      id: 3,
      name: "Shark Bay",
      regionName: "",
      deployed: true,
      isCollection: true,
      historicMax: 3.7,
      polygon: {
        type: "Point",
        coordinates: [114.165115356, -21.931162834],
      },
      collectionData: {
        satelliteTemperature: 3.7,
        sstAnomaly: 3.7,
        degreeHeatingDays: 3.7 * 7,
        topTemperature: 3.7,
        bottomTemperature: 3.7,
        weeklyAlert: 4,
      },
    }),
    generateMockReef({
      id: 4,
      name: "Polar Bear Lair",
      regionName: "",
      deployed: true,
      isCollection: true,
      historicMax: 4.8,
      polygon: {
        type: "Point",
        coordinates: [113.74035, -23.136667],
      },
      collectionData: {
        satelliteTemperature: 4.8,
        sstAnomaly: 4.8,
        degreeHeatingDays: 4.8 * 7,
        topTemperature: 4.8,
        bottomTemperature: 4.8,
        weeklyAlert: 3,
      },
    }),
    generateMockReef({
      id: 5,
      name: "Parrotfish Hideout",
      regionName: "",
      deployed: true,
      isCollection: true,
      historicMax: 0.2,
      polygon: {
        type: "Point",
        coordinates: [113.071111, -25.444667],
      },
      collectionData: {
        satelliteTemperature: 0.2,
        sstAnomaly: 0.2,
        degreeHeatingDays: 0.2 * 7,
        topTemperature: 0.2,
        bottomTemperature: 0.2,
        weeklyAlert: 3,
      },
    }),
    generateMockReef({
      id: 6,
      name: "Pirate's Bay",
      regionName: "",
      deployed: true,
      isCollection: true,
      historicMax: 2.5,
      polygon: {
        type: "Point",
        coordinates: [113.808517, -28.851383],
      },
      collectionData: {
        satelliteTemperature: 2.5,
        sstAnomaly: 2.5,
        degreeHeatingDays: 2.5 * 7,
        topTemperature: 2.5,
        bottomTemperature: 2.5,
        weeklyAlert: 2,
      },
    }),
    generateMockReef({
      id: 7,
      name: "Ningaloo Coast",
      regionName: "",
      deployed: false,
      isCollection: true,
      historicMax: -2.3,
      polygon: {
        type: "Point",
        coordinates: [121.874544857, -18.443135757],
      },
      collectionData: {
        satelliteTemperature: -2.3,
        sstAnomaly: -2.3,
        degreeHeatingDays: -2.3 * 7,
        topTemperature: -2.3,
        bottomTemperature: -2.3,
        weeklyAlert: 2,
      },
    }),
    generateMockReef({
      id: 8,
      name: "Penguin Cove",
      regionName: "",
      deployed: false,
      isCollection: true,
      historicMax: 4,
      polygon: {
        type: "Point",
        coordinates: [130.7829, -12.167],
      },
      collectionData: {
        satelliteTemperature: 4,
        sstAnomaly: 4,
        degreeHeatingDays: 4 * 7,
        topTemperature: 4,
        bottomTemperature: 4,
        weeklyAlert: 0,
      },
    }),
    generateMockReef({
      id: 9,
      name: "Parker Point",
      regionName: "",
      deployed: false,
      isCollection: true,
      historicMax: 5.1,
      polygon: {
        type: "Point",
        coordinates: [115.52544, -32.02742],
      },
      collectionData: {
        satelliteTemperature: 5.1,
        sstAnomaly: 5.1,
        degreeHeatingDays: 5.1 * 7,
        topTemperature: 5.1,
        bottomTemperature: 5.1,
        weeklyAlert: 1,
      },
    }),
    generateMockReef({
      id: 10,
      name: "Little Island",
      regionName: "",
      deployed: false,
      isCollection: true,
      historicMax: 6.4,
      polygon: {
        type: "Point",
        coordinates: [115.707943439, -31.81277605],
      },
      collectionData: {
        satelliteTemperature: 6.4,
        sstAnomaly: 6.4,
        degreeHeatingDays: 6.4 * 7,
        topTemperature: 6.4,
        bottomTemperature: 6.4,
        weeklyAlert: 1,
      },
    }),
    generateMockReef({
      id: 11,
      name: "Mermaid Reef",
      regionName: "",
      deployed: true,
      isCollection: true,
      historicMax: 2.3,
      polygon: {
        type: "Point",
        coordinates: [119.6, -17.1],
      },
      collectionData: {
        satelliteTemperature: 2.3,
        sstAnomaly: 2.3,
        degreeHeatingDays: 2.3 * 7,
        topTemperature: 2.3,
        bottomTemperature: 2.3,
        weeklyAlert: 1,
      },
    }),
    generateMockReef({
      id: 12,
      name: "Imperieuse Reef",
      regionName: "",
      deployed: false,
      isCollection: true,
      historicMax: 4.2,
      polygon: {
        type: "Point",
        coordinates: [118.9, -17.6],
      },
      collectionData: {
        satelliteTemperature: 4.2,
        sstAnomaly: 4.2,
        degreeHeatingDays: 4.2 * 7,
        topTemperature: 4.2,
        bottomTemperature: 4.2,
        weeklyAlert: 1,
      },
    }),
    generateMockReef({
      id: 13,
      name: "Cape Leveque",
      regionName: "",
      deployed: false,
      isCollection: true,
      historicMax: 9.1,
      polygon: {
        type: "Point",
        coordinates: [122.926025391, -16.402988391],
      },
      collectionData: {
        satelliteTemperature: 9.1,
        sstAnomaly: 9.1,
        degreeHeatingDays: 9.1 * 7,
        topTemperature: 9.1,
        bottomTemperature: 9.1,
        weeklyAlert: 1,
      },
    }),
    generateMockReef({
      id: 14,
      name: "Off Jackson Island",
      regionName: "",
      deployed: false,
      isCollection: true,
      historicMax: 8.4,
      polygon: {
        type: "Point",
        coordinates: [124.716053719, -15.1463693],
      },
      collectionData: {
        satelliteTemperature: 8.4,
        sstAnomaly: 8.4,
        degreeHeatingDays: 8.4 * 7,
        topTemperature: 8.4,
        bottomTemperature: 8.4,
        weeklyAlert: 1,
      },
    }),
    generateMockReef({
      id: 15,
      name: "South Scott",
      regionName: "",
      deployed: false,
      isCollection: true,
      historicMax: 6.8,
      polygon: {
        type: "Point",
        coordinates: [121.8, -14.1],
      },
      collectionData: {
        satelliteTemperature: 6.8,
        sstAnomaly: 6.8,
        degreeHeatingDays: 6.8 * 7,
        topTemperature: 6.8,
        bottomTemperature: 6.8,
        weeklyAlert: 1,
      },
    }),
  ],
};
