export const sondeConfig: { [key: string]: any | undefined } = {
  salinity: {
    title: "Salinity",
    units: "psu",
    description: "",
    visibility: "public",
    order: 1,
  },
  turbidity: {
    title: "Turbidity",
    units: "fnu",
    description: "",
    visibility: "public",
    order: 2,
  },
  bottom_temperature: {
    title: "Temperature at Depth",
    units: "°C",
    description: "",
    visibility: "public",
    order: 4,
  },
  odo_saturation: {
    title: "Optical Dissolved Oxygen (saturation)",
    units: "% sat",
    description: "",
    visibility: "public",
    order: 4,
  },
  ph: {
    title: "Acidity",
    units: "pH",
    description: "",
    visibility: "public",
    order: 5,
  },
  cholorophyll_rfu: {
    title: "Chlorophyll Relative Fluorescence",
    units: "RFU",
    description: "",
    visibility: "public",
    order: 8,
  },
  cholorophyll_concentration: {
    title: "Chlorophyll Concentration",
    units: "µg/L",
    description: "",
    visibility: "public",
    order: 7,
  },
  conductivity: {
    title: "Conductivity",
    units: "µS/cm",
    description: "",
    visibility: "public",
    order: 8,
  },
  water_depth: {
    title: "Depth",
    units: "m",
    description: "",
    visibility: "public",
    order: 7,
  },
  odo_concentration: {
    title: "Optical Dissolved Oxygen (concentration)",
    units: "mg/L",
    description: "",
    visibility: "public",
    order: 7,
  },
  specific_conductance: {
    title: "Specific Conductance",
    units: "µS/cm",
    description: "",
    visibility: "public",
    order: 8,
  },
  tds: {
    title: "Concentration of Dissolved Particles (TDS)",
    units: "mg/L",
    description: "",
    visibility: "public",
    order: 8,
  },
  total_suspended_solids: {
    title: "Total Suspended Solids",
    units: "mg/L",
    description: "",
    visibility: "public",
    order: 8,
  },
  sonde_wiper_position: {
    title: "Sonde Wiper Position",
    units: "V",
    description: "",
    visibility: "admin",
    order: 8,
  },
  ph_mv: {
    title: "Acidity Conrol Voltage",
    units: "mV",
    description: "",
    visibility: "admin",
    order: 8,
  },
  sonde_battery_voltage: {
    title: "Sonde Battery",
    units: "V",
    description: "",
    visibility: "admin",
    order: 9,
  },
  sonde_cable_power_voltage: {
    title: "Sonder Cable Power Voltage",
    units: "V",
    description: "",
    visibility: "admin",
    order: 9,
  },
};

export function getSondeConfig(configKey: string) {
  return sondeConfig[configKey] || {};
}
